journal/urls.py
from django.urls import path
from journal import views
app_name = "journal"
urlpatterns = [
    path("",views.journal_index, name="journal_index"),
    path("<int:pk>/", views.journal_detail, name="journal_detail"),
    path("<category>/", views.journal_category, name="journal_category"),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path("journal/", include("journal.urls")),
]

projects/urls.py
from typing import List, Any

from django.urls import path
from projects import views

app_name = "projects"
urlpatterns = [
    path('', views.all_projects,name='all_projects'),
    path('<int:pk>',views.project_detail, name='project_detail'),
    ]

journal/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=20)

class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField('Category', related_name='posts')

journal/views.py
from django.shortcuts import render
from journal.models import Post
# Create your views here.


def journal_index(request):
    posts = Post.objects.all().order_by('-created_on')
    context = {
        "posts": posts
    }
    return render(request, "journal/journal_index.html", context)


def journal_category(request, category):
    posts = Post.objects.filter(
        categories__name__contains=category
    ).order_by(
        '-created_on'
    )
    context = {
        "category": category,
        "posts": posts
    }
    return render(request, "journal/journal_category.html", context)


def journal_detail(request, pk):
    post = Post.objects.get(pk=pk)
    context = {
        "post": post,
    }
    return render(request, "journal/journal_detail.html", context)

journal/templates/journal/journal_category.html
{% extends "projects/base.html" %}
{% block content %}
<div class="col-md-8 offset-md-2">
    <h1>{{ category | title }}</h1>
    <hr>
    {% for post in posts %}
        <h2><a href="{% url 'journal:journal_detail' post.pk%}">{{ post.title }}</a></h2>
        <small>
            {{ post.created_on.date }} |&nbsp;
            Categories:&nbsp;
            {% for category in post.categories.all %}
            <a href="{% url 'journal:journal_category' category.name %}">
                {{ category.name }}
            </a>&nbsp;
            {% endfor %}
        </small>
        <p>{{ post.body | slice:":400" }}...</p>
    {% endfor %}
</div>
{% endblock %}

journal/templates/journal/journal_detail.html
{% extends "projects/base.html" %}
{% block content %}
<div class="col-md-8 offset-md-2">
    <h1>{{ post.title }}</h1>
    <p>{{ post.body | linebreaks }}</p>
    <small>
        {{ post.created_on.date }} |&nbsp;
        Categories:&nbsp;
        {% for category in post.categories.all %}
        <a href="{% url 'journal:journal_category' category.name %}">
            {{ category.name }}
        </a>&nbsp;
        {% endfor %}
    </small>

</div>
{% endblock %}

journal/templates/journal/journal_index.html
{% extends "base.html" %}
{% block page_content %}
<div class="col-md-8 offset-md-2">
    <h1>Journal Index</h1>
    <hr>
    {% for post in posts %}
    <h2><a href="{% url 'journal_detail' post.pk%}">{{ post.title }}</a></h2>
    <small>
        {{ post.created_on.date }} |&nbsp;
        Categories:&nbsp;
        {% for category in post.categories.all %}
        <a href="{% url 'journal_category' category.name %}">
            {{ category.name }}
        </a>&nbsp;
        {% endfor %}
    </small>
    <p>{{ post.body | slice:":400" }}...</p>
    {% endfor %}
</div>
{% endblock %}

projects/templates/projects/all_projects.html
{% extends 'projects/base.html' %}
{% load static %}

{% block content %}
        <h1>Projects</h1>
        <div class="row">
        {% for project in projects %}
            <div class="col-md-4">
                <div class="card mb-2">
                    <img class="card-img-top" src="{% static project.image %}">
                    <div class="card-body">
                        <h5 class="card-title">{{ project.title }}</h5>
                        <p class="card-text">{{ project.description }}</p>
                        <a href="{% url 'projects:project_detail' project.pk %}"
                        class="btn btn-primary">
                            Read More
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
{% endblock %}

projects/templates/projects/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Portfolio</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'projects:all_projects' %}">Dan Walsh</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'projects:all_projects' %}">Slackline Portfolio</a>
            </li>
          </ul>
        </div>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'journal:journal_index' %}">Journal</a>
            </li>
          </ul>
        </div>
    </div>
</nav>

<div class="container">
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

projects/templates/projects/detail.html
{% extends 'projects/base.html' %}
{% load static %}
{% block content %}
    <h1>{{ project.title }}</h1>
    <div class ="row">
        <div class ="col-md-8">
            <img src="{% static project.image %}" alt="{{ project.description }}" width="75%" height="100%">
        </div>
        <div class="col-md-4">
            <p>{{ project.date }}</p>
            <p>Organization: {{ project.organization }}</p>
            <p>Position held: {{ project.position }}</p>
            <h5>About the project</h5>
            <p>{{ project.description}}</p>
        </div>
    </div>
{% endblock%}